### ISSUE TITLE
关于域名问题

### ISSUE THREAD

**Issue by maobasix** [MoRan23/GZCTF-Auto#3]
如果在使用一键脚本时选择域名会造成无法搭建，Ubuntu22.0.4

**Comment by MoRan23** [comment]
> 如果在使用一键脚本时选择域名会造成无法搭建，Ubuntu22.0.4

你好有错误的具体信息吗

**Comment by maobasix** [comment]
> > 如果在使用一键脚本时选择域名会造成无法搭建，Ubuntu22.0.4
> 
> 你好有错误的具体信息吗，我自己搭建的时候是没有问题的，你可以检查一下域名是否解析成功了

Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable ufw
Removed /etc/systemd/system/multi-user.target.wants/ufw.service.
Failed to disable unit: Unit file iptables.service does not exist.
# Source: Caddy
# Site: https://github.com/caddyserver/caddy
# Repository: Caddy / stable
# Description: Fast, multi-platform web server with automatic HTTPS


deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main

deb-src [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
Hit:1 http://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy InRelease
Hit:2 http://mirrors.ustc.edu.cn/ubuntu jammy InRelease                                                                                                    
Hit:3 http://mirrors.ustc.edu.cn/ubuntu jammy-updates InRelease                                                                                            
Hit:4 http://mirrors.ustc.edu.cn/ubuntu jammy-backports InRelease                                    
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease                                     
Get:6 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [8266 B]
Get:7 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version/main amd64 Packages [3643 B]
Fetched 11.9 kB in 2s (6197 B/s)    
Reading package lists... Done
W: http://mirrors.aliyun.com/docker-ce/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libflashrom1 libftdi1-2
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  caddy
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 14.7 MB of archives.
After this operation, 40.8 MB of additional disk space will be used.
Get:1 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version/main amd64 caddy amd64 2.8.4 [14.7 MB]
Fetched 14.7 MB in 4s (3427 kB/s)
Selecting previously unselected package caddy.
(Reading database ... 64706 files and directories currently installed.)
Preparing to unpack .../archives/caddy_2.8.4_amd64.deb ...
Unpacking caddy (2.8.4) ...
Setting up caddy (2.8.4) ...
Created symlink /etc/systemd/system/multi-user.target.wants/caddy.service → /lib/systemd/system/caddy.service.
Processing triggers for man-db (2.10.2-1) ...
NEEDRESTART-VER: 3.5
NEEDRESTART-KCUR: 5.15.0-30-generic
NEEDRESTART-KEXP: 5.15.0-30-generic
NEEDRESTART-KSTA: 1
NEEDRESTART-SVC: cron.service
NEEDRESTART-SVC: dbus.service
NEEDRESTART-SVC: getty@tty1.service
NEEDRESTART-SVC: networkd-dispatcher.service
NEEDRESTART-SVC: packagekit.service
NEEDRESTART-SVC: polkit.service
NEEDRESTART-SVC: serial-getty@ttyS0.service
NEEDRESTART-SVC: systemd-logind.service
NEEDRESTART-SVC: systemd-manager
NEEDRESTART-SVC: udisks2.service
NEEDRESTART-SVC: unattended-upgrades.service
NEEDRESTART-SVC: user@0.service
WARN[0000] /root/GZCTF/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
invalid hostPort: PORT
============
||部署成功!||
============
实际上没有容器启动

**Comment by MoRan23** [comment]
> > > 如果在使用一键脚本时选择域名会造成无法搭建，Ubuntu22.0.4
> > 
> > 
> > 你好有错误的具体信息吗，我自己搭建的时候是没有问题的，你可以检查一下域名是否解析成功了
> 
> Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install. Executing: /lib/systemd/systemd-sysv-install disable ufw Removed /etc/systemd/system/multi-user.target.wants/ufw.service. Failed to disable unit: Unit file iptables.service does not exist.
> 
> # Source: Caddy
> # Site: https://github.com/caddyserver/caddy
> # Repository: Caddy / stable
> # Description: Fast, multi-platform web server with automatic HTTPS
> deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
> 
> # deb-src [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
> Hit:1 http://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy InRelease
> Hit:2 http://mirrors.ustc.edu.cn/ubuntu jammy InRelease
> Hit:3 http://mirrors.ustc.edu.cn/ubuntu jammy-updates InRelease
> Hit:4 http://mirrors.ustc.edu.cn/ubuntu jammy-backports InRelease
> Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
> Get:6 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [8266 B]
> Get:7 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version/main amd64 Packages [3643 B]
> Fetched 11.9 kB in 2s (6197 B/s)
> Reading package lists... Done
> W: http://mirrors.aliyun.com/docker-ce/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
> libflashrom1 libftdi1-2
> Use 'sudo apt autoremove' to remove them.
> The following NEW packages will be installed:
> caddy
> 0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
> Need to get 14.7 MB of archives.
> After this operation, 40.8 MB of additional disk space will be used.
> Get:1 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version/main amd64 caddy amd64 2.8.4 [14.7 MB]
> Fetched 14.7 MB in 4s (3427 kB/s)
> Selecting previously unselected package caddy.
> (Reading database ... 64706 files and directories currently installed.)
> Preparing to unpack .../archives/caddy_2.8.4_amd64.deb ...
> Unpacking caddy (2.8.4) ...
> Setting up caddy (2.8.4) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/caddy.service → /lib/systemd/system/caddy.service.
> Processing triggers for man-db (2.10.2-1) ...
> NEEDRESTART-VER: 3.5
> NEEDRESTART-KCUR: 5.15.0-30-generic
> NEEDRESTART-KEXP: 5.15.0-30-generic
> NEEDRESTART-KSTA: 1
> NEEDRESTART-SVC: cron.service
> NEEDRESTART-SVC: dbus.service
> NEEDRESTART-SVC: [getty@tty1.service](mailto:getty@tty1.service)
> NEEDRESTART-SVC: networkd-dispatcher.service
> NEEDRESTART-SVC: packagekit.service
> NEEDRESTART-SVC: polkit.service
> NEEDRESTART-SVC: [serial-getty@ttyS0.service](mailto:serial-getty@ttyS0.service)
> NEEDRESTART-SVC: systemd-logind.service
> NEEDRESTART-SVC: systemd-manager
> NEEDRESTART-SVC: udisks2.service
> NEEDRESTART-SVC: unattended-upgrades.service
> NEEDRESTART-SVC: [user@0.service](mailto:user@0.service)
> WARN[0000] /root/GZCTF/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
> invalid hostPort: PORT
> # ||部署成功!||
> 实际上没有容器启动

ok,我了解了，正在着手修复，稍后回复

**Comment by MoRan23** [comment]
> > > 如果在使用一键脚本时选择域名会造成无法搭建，Ubuntu22.0.4
> > 
> > 
> > 你好有错误的具体信息吗，我自己搭建的时候是没有问题的，你可以检查一下域名是否解析成功了
> 
> Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install. Executing: /lib/systemd/systemd-sysv-install disable ufw Removed /etc/systemd/system/multi-user.target.wants/ufw.service. Failed to disable unit: Unit file iptables.service does not exist.
> 
> # Source: Caddy
> # Site: https://github.com/caddyserver/caddy
> # Repository: Caddy / stable
> # Description: Fast, multi-platform web server with automatic HTTPS
> deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
> 
> # deb-src [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
> Hit:1 http://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy InRelease
> Hit:2 http://mirrors.ustc.edu.cn/ubuntu jammy InRelease
> Hit:3 http://mirrors.ustc.edu.cn/ubuntu jammy-updates InRelease
> Hit:4 http://mirrors.ustc.edu.cn/ubuntu jammy-backports InRelease
> Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
> Get:6 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [8266 B]
> Get:7 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version/main amd64 Packages [3643 B]
> Fetched 11.9 kB in 2s (6197 B/s)
> Reading package lists... Done
> W: http://mirrors.aliyun.com/docker-ce/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
> libflashrom1 libftdi1-2
> Use 'sudo apt autoremove' to remove them.
> The following NEW packages will be installed:
> caddy
> 0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
> Need to get 14.7 MB of archives.
> After this operation, 40.8 MB of additional disk space will be used.
> Get:1 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version/main amd64 caddy amd64 2.8.4 [14.7 MB]
> Fetched 14.7 MB in 4s (3427 kB/s)
> Selecting previously unselected package caddy.
> (Reading database ... 64706 files and directories currently installed.)
> Preparing to unpack .../archives/caddy_2.8.4_amd64.deb ...
> Unpacking caddy (2.8.4) ...
> Setting up caddy (2.8.4) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/caddy.service → /lib/systemd/system/caddy.service.
> Processing triggers for man-db (2.10.2-1) ...
> NEEDRESTART-VER: 3.5
> NEEDRESTART-KCUR: 5.15.0-30-generic
> NEEDRESTART-KEXP: 5.15.0-30-generic
> NEEDRESTART-KSTA: 1
> NEEDRESTART-SVC: cron.service
> NEEDRESTART-SVC: dbus.service
> NEEDRESTART-SVC: [getty@tty1.service](mailto:getty@tty1.service)
> NEEDRESTART-SVC: networkd-dispatcher.service
> NEEDRESTART-SVC: packagekit.service
> NEEDRESTART-SVC: polkit.service
> NEEDRESTART-SVC: [serial-getty@ttyS0.service](mailto:serial-getty@ttyS0.service)
> NEEDRESTART-SVC: systemd-logind.service
> NEEDRESTART-SVC: systemd-manager
> NEEDRESTART-SVC: udisks2.service
> NEEDRESTART-SVC: unattended-upgrades.service
> NEEDRESTART-SVC: [user@0.service](mailto:user@0.service)
> WARN[0000] /root/GZCTF/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
> invalid hostPort: PORT
> # ||部署成功!||
> 实际上没有容器启动

已经推送，删除原脚本后再次使用安装命令谢谢
