### ISSUE TITLE
WSL2部署失败

### ISSUE THREAD

**Issue by SeimoDev** [MoRan23/GZCTF-Auto#5]
Ubuntu 22.04系统
错误日志：
```
Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable ufw
Failed to disable unit: Unit file iptables.service does not exist.
mkdir: cannot create directory ‘GZCTF’: File exists
未解析域名, 跳过caddy配置...
empty compose file
GZCTF 启动失败.
```

**Comment by MoRan23** [comment]
> Ubuntu 22.04系统 错误日志：
> 
> ```
> Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install disable ufw
> Failed to disable unit: Unit file iptables.service does not exist.
> mkdir: cannot create directory ‘GZCTF’: File exists
> 未解析域名, 跳过caddy配置...
> empty compose file
> GZCTF 启动失败.
> ```

看看文件结构

**Comment by SeimoDev** [comment]
.
├── GZCTF
│   ├── appsettings.json
│   └── docker-compose.yaml
└── install.sh

1 directory, 3 files

**Comment by MoRan23** [comment]
> . ├── GZCTF │   ├── appsettings.json │   └── docker-compose.yaml └── install.sh
> 
> 1 directory, 3 files

先都删掉，重新下一下脚本然后允许，给我一个完整的日志，可以截图

**Comment by SeimoDev** [comment]
解决了，在`42-49行`都添加`--no-check-certificate`参数即可
